# This file was generated by nvfetcher, please do not modify it manually.
{ fetchFromGitHub
, ...
}: {
  gh-poi = {
    pname = "gh-poi";
    version = "v0.9.0";
    src = fetchFromGitHub {
      owner = "seachicken";
      repo = "gh-poi";
      rev = "v0.9.0";
      fetchSubmodules = false;
      sha256 = "sha256-7lvqiD0yitc3kvXLD9AtCBCp+F+fqRJyLdnio1R6oP8=";
    };
  };
  homebrew-emacs-plus = {
    pname = "homebrew-emacs-plus";
    version = "889a5caf46ccfca3d96c6f770eca7f69ba2d34f8";
    src = fetchFromGitHub {
      owner = "d12frosted";
      repo = "homebrew-emacs-plus";
      rev = "889a5caf46ccfca3d96c6f770eca7f69ba2d34f8";
      fetchSubmodules = false;
      sha256 = "sha256-ybTIpi/KctiTzDAE8JcjZuFLnfoWQTk/zTYyuNHP8+w=";
    };
  };
}
