# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  aerospace = {
    pname = "aerospace";
    version = "v0.11.2-Beta";
    src = fetchFromGitHub {
      owner = "nikitabobko";
      repo = "AeroSpace";
      rev = "v0.11.2-Beta";
      fetchSubmodules = false;
      sha256 = "sha256-PK8dtwAbUs034ObGCy4FEKtOTirujfEfhzB9Cx7Lyp8=";
    };
  };
  gh-poi = {
    pname = "gh-poi";
    version = "v0.10.1";
    src = fetchFromGitHub {
      owner = "seachicken";
      repo = "gh-poi";
      rev = "v0.10.1";
      fetchSubmodules = false;
      sha256 = "sha256-ZQkXXaa4n88bJdgP2FSXtgBrUi39teO98SzZq+I5doM=";
    };
  };
}
