# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  fenix = {
    pname = "fenix";
    version = "9ecf5e7d800ace001320da8acadd4a3deb872a83";
    src = fetchFromGitHub {
      owner = "nix-community";
      repo = "fenix";
      rev = "9ecf5e7d800ace001320da8acadd4a3deb872a83";
      fetchSubmodules = false;
      sha256 = "sha256-88f0KK8h6tGIP4Na5RJDKs0S+7WsGGaCGNkLj/bPV3g=";
    };
    date = "2024-08-26";
  };
  firefox-addons = {
    pname = "firefox-addons";
    version = "70645c904b41b9ddf70f7218898c48df93e8254f";
    src = fetchgit {
      url = "https://gitlab.com/rycee/nur-expressions.git";
      rev = "70645c904b41b9ddf70f7218898c48df93e8254f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-XJ8B9ecksgZBlWV9pnDgBWVePyHDg/cLYJ/6YF/RdRA=";
    };
    date = "2024-08-26";
  };
  git-hooks = {
    pname = "git-hooks";
    version = "c8a54057aae480c56e28ef3e14e4960628ac495b";
    src = fetchFromGitHub {
      owner = "cachix";
      repo = "git-hooks.nix";
      rev = "c8a54057aae480c56e28ef3e14e4960628ac495b";
      fetchSubmodules = false;
      sha256 = "sha256-9etXEOUtzeMgqg1u0wp+EdwG7RpmrAZ2yX516bMj2aE=";
    };
    date = "2024-08-23";
  };
  github-actions = {
    pname = "github-actions";
    version = "622f829f5fe69310a866c8a6cd07e747c44ef820";
    src = fetchFromGitHub {
      owner = "nix-community";
      repo = "nix-github-actions";
      rev = "622f829f5fe69310a866c8a6cd07e747c44ef820";
      fetchSubmodules = false;
      sha256 = "sha256-uPlLYH2S0ACj0IcgaK9Lsf4spmJoGejR9DotXiXSBZQ=";
    };
    date = "2024-07-04";
  };
  home-manager = {
    pname = "home-manager";
    version = "e1391fb22e18a36f57e6999c7a9f966dc80ac073";
    src = fetchFromGitHub {
      owner = "nix-community";
      repo = "home-manager";
      rev = "e1391fb22e18a36f57e6999c7a9f966dc80ac073";
      fetchSubmodules = false;
      sha256 = "sha256-A0vrUB6x82/jvf17qPCpxaM+ulJnD8YZwH9Ci0BsAzE=";
    };
    date = "2024-07-03";
  };
  lix-module = {
    pname = "lix-module";
    version = "2.91.0";
    src = fetchTarball {
      url = "https://git.lix.systems/lix-project/nixos-module/archive/2.91.0.tar.gz";
      sha256 = "sha256-zNW/rqNJwhq2lYmQf19wJerRuNimjhxHKmzrWWFJYts=";
    };
  };
  neovim-nightly-overlay = {
    pname = "neovim-nightly-overlay";
    version = "e87be8db9b99173d375a9ba3b4fd3a57aaa7386e";
    src = fetchFromGitHub {
      owner = "nix-community";
      repo = "neovim-nightly-overlay";
      rev = "e87be8db9b99173d375a9ba3b4fd3a57aaa7386e";
      fetchSubmodules = false;
      sha256 = "sha256-UPASmzd46/5P118t2fg/pIMid5yxEJSmXpPRuKawxUE=";
    };
    date = "2024-08-26";
  };
  nix-darwin = {
    pname = "nix-darwin";
    version = "ac5694a0b855a981e81b4d9f14052e3ff46ca39e";
    src = fetchFromGitHub {
      owner = "LnL7";
      repo = "nix-darwin";
      rev = "ac5694a0b855a981e81b4d9f14052e3ff46ca39e";
      fetchSubmodules = false;
      sha256 = "sha256-zv8C9RNa86CIpyHwPIVO/k+5TfM8ZbjGwOOpTe1grls=";
    };
    date = "2024-08-25";
  };
  nix-homebrew = {
    pname = "nix-homebrew";
    version = "0afc51fd86693c73e4b60be8ed8c782c4c09b4cc";
    src = fetchFromGitHub {
      owner = "zhaofengli-wip";
      repo = "nix-homebrew";
      rev = "0afc51fd86693c73e4b60be8ed8c782c4c09b4cc";
      fetchSubmodules = false;
      sha256 = "sha256-FNK5ZxmNC+V/wOuioc5HqkUy0ld4eW3NqcsZHLYg9HI=";
    };
    date = "2024-06-30";
  };
  nixpkgs-firefox-darwin = {
    pname = "nixpkgs-firefox-darwin";
    version = "44aa30f3266b53aa01208e0b1a4ad0ea440bbf7e";
    src = fetchFromGitHub {
      owner = "bandithedoge";
      repo = "nixpkgs-firefox-darwin";
      rev = "44aa30f3266b53aa01208e0b1a4ad0ea440bbf7e";
      fetchSubmodules = false;
      sha256 = "sha256-NZrAR/mmTHNjX79CYLMtELdbfcHOs2k1G6bJMaKGA7s=";
    };
    date = "2024-08-26";
  };
  nixpkgs-master = {
    pname = "nixpkgs-master";
    version = "9c50de8b57f060144c676654d9773db934a2b2c6";
    src = fetchgit {
      url = "https://github.com/NixOS/nixpkgs.git";
      rev = "9c50de8b57f060144c676654d9773db934a2b2c6";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-FuMdXIMCswz3qX8VrROBpZdAzYqvwaIvcetbbIsPRsc=";
    };
    date = "2024-08-26";
  };
}
