name: Install Lix

description: "Set up Lix"

inputs:
  system:
    description: "The Nix system enumeration for the runner."
    required: true

  GH_SSH_KEY:
    description: ""
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Lix
      uses: DeterminateSystems/nix-installer-action@v13
      with:
        source-url: https://install.lix.systems/lix/lix-installer-${{ inputs.system }}
        diagnostic-endpoint: ""
        extra-conf: |
          auto-optimise-store = true
          extra-experimental-features = nix-command flakes pipe-operator

    - name: Set up cache
      uses: DeterminateSystems/magic-nix-cache-action@b46e247b898aa56e6d2d2e728dc6df6c84fdb738 # v7
      with:
        diagnostic-endpoint: ""

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@dc588b651fe13675774614f8e6a936a468676387 # v0.9.0
      with:
        ssh-private-key: ${{ inputs.GH_SSH_KEY }}
