args: [
  (import ./utils.nix args)
  (import ./default-el.nix args)
  (import ./early-init.nix args)

  (import ./frame.nix args)
  (import ./font.nix args)
  (import ./general.nix args)

  (import ./nordic-night.nix args)
  (import ./nix.nix args)
  (import ./lua.nix args)
  (import ./org.nix args)
  (import ./magit.nix args)
  (import ./envrc.nix args)
  (import ./aggressive-indent.nix args)
  (import ./corfu.nix args)
  (import ./vertico.nix args)
  (import ./embark.nix args)
  (import ./marginalia.nix args)
  (import ./orderless.nix args)
  (import ./consult.nix args)
  (import ./projectile.nix args)
  (import ./meow.nix args)
  (import ./ligature.nix args)
  (import ./prism.nix args)
  (import ./macrostep.nix args)
  (import ./esup.nix args)
  (import ./puni.nix args)
  (import ./gcmh.nix args)
  (import ./diminish.nix args)
  (import ./doom-modeline.nix args)
  (import ./fixed-pitch-mode.nix args)
  (import ./clojure.nix args)
  (import ./rust.nix args)
]
